apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesh-customersapi
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mesh-customersapi
  template:
    metadata:
      labels:
        app: mesh-customersapi
    spec:
      containers:
        - name: customersapi
          image: bytebeam/mesh-customersapi:0.1
          env:
            - name: JAEGER_SERVICE_NAME
              value: mesh-customersapi
            - name: JAEGER_AGENT_HOST
              value: localhost
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: ASPNETCORE_URLS
              value: http://+:5001
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          ports:
            - containerPort: 5001
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesh-ordersapi
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mesh-ordersapi
  template:
    metadata:
      labels:
        app: mesh-ordersapi
    spec:
      containers:
        - name: ordersapi
          image: bytebeam/mesh-ordersapi:0.1
          env:
            - name: JAEGER_SERVICE_NAME
              value: mesh-ordersapi
            - name: JAEGER_AGENT_HOST
              value: localhost
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: ASPNETCORE_URLS
              value: http://+:5002
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          ports:
            - containerPort: 5002
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesh-frontend
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mesh-frontend
  template:
    metadata:
      labels:
        app: mesh-frontend
    spec:
      containers:
        - name: frontend
          image: bytebeam/mesh-frontend:0.1
          env:
            - name: JAEGER_SERVICE_NAME
              value: mesh-frontend
            - name: JAEGER_AGENT_HOST
              value: localhost
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: ASPNETCORE_URLS
              value: http://+:5000
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          ports:
            - containerPort: 5000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mesh-frontend
  labels:
    app: mesh-frontend
spec:
  selector:
    app: mesh-frontend
  ports:
    - name: http
      port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mesh-customersapi
  labels:
    app: mesh-customersapi
spec:
  selector:
    app: mesh-customersapi
  ports:
    - name: http
      port: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: mesh-ordersapi
  labels:
    app: mesh-ordersapi
spec:
  selector:
    app: mesh-ordersapi
  ports:
    - name: http
      port: 5002