apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: ca-key-pair
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: whoami.dev.local-cert
spec:
  secretName: whoami.dev.local-cert
  commonName: whoami.dev.local
  issuerRef:
    name: ca-issuer
    kind: Issuer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - image: containous/whoami
          name: whoami
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  selector:
    app: whoami
  type: ClusterIP
  ports:
    - name: http
      port: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: whoami
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
spec:
  rules:
    - host: whoami.dev.local
      http:
        paths:
          - path: /
            backend:
              serviceName: whoami
              servicePort: 80
  tls:
    - hosts:
      - whoami.dev.local
      secretName: whoami.dev.local-cert